config/routes.rb
Rails.application.routes.draw do
  devise_for :visitors
  #root to: 'books#index'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    root to: 'pages#home'

    resources :books
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get '/users', to: 'users#new'
    resources :users
    #match ':controller(/:action(/:id))(.:format)'
    resources :segments
  end
end

app/models/segment.rb
class Segment < ApplicationRecord
  has_many :users, through: :books
  has_many :visitors, through: :books
  has_many :books
  has_one_attached :image

end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController

  before_action :set_segment, only: [:show, :edit, :update, :destroy]

  # GET /s
  # GET /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url, notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def segment_params
      params.require(:segment).permit(:location, :description, :image)
    end
  end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_with(model: segment, local: true) do |form| %>
  <% if segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% segment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

<!-- IMAGE STORAGE BELLOW -->
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/segments/edit.html.erb
<h1>Editing Segment</h1>

<%= render 'form', segment: @segment %>

<%= link_to 'Show', @segment %> |
<%= link_to 'Back', segments_path %>

app/views/segments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Segments of the Community Mural</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.location %></td>
        <td><%= segment.description %></td>
        <td><%= link_to 'Show', segment %></td>
        <td><%= link_to 'Edit', edit_segment_path(segment) %></td>
        <td><%= link_to 'Destroy', segment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segment', new_segment_path %>

app/views/segments/new.html.erb
<h1>New Segment</h1>

<%= render 'form', segment: @segment %>

<%= link_to 'Back', segments_path %>

app/views/segments/show.html.erb
show segment here
<p id="notice"><%= notice %></p>

<div class="field">
  <p>
    <strong>Location:</strong>
    <%= @segment.location %>
  </p>
</div>

<div class="field">
  <p>
    <strong>Comment:</strong>
    <%= @segment.description %>
  </p>
</div>

<div style="width:400px; height:auto">
  <%= link_to image_tag(@segment.image, style:'width:100%'), segments_path %>
</div>

<%= link_to 'Edit', edit_segment_path(@segment) %> |
<%= link_to 'Back', segments_path %>